server: server.cpp ../../Utils/src/serialization.cpp
	g++ server.cpp ../../Utils/src/serialization.cpp -o server -std=c++11 -pthread -lpthread `mysql_config --cflags --libs` -Wno-error=format-security
